### ISSUE TITLE
When closing a card, I'd like to stay in the same position in the list

### ISSUE THREAD

**Issue by michelgrootjans** [infovore/voip-flashcards#4]
When opening the app on my phone, I see a list:
- One at a time
- I'd like to speak
- ...

Steps to reproduce:
1) I scroll down in the list
2) I click on an item (and show it to my teammates)
3) I click on it again to close it
4) I would like to return to the same position I was in step 2

**Comment by infovore** [comment]
Try now? I made some tweaks in ddf78c6d24c0abca4bde738b4de4cc02c5a4de56 that should fix it...

**Comment by michelgrootjans** [comment]
Works for me. Thank you.
